# Generated by Django 4.1 on 2022-08-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ably_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('verification_code', models.CharField(max_length=6)),
                ('trial', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'phone_auth',
            },
        ),
    ]
